import { create } from 'zustand'
import { createJSONStorage, persist } from 'zustand/middleware'
import type { CustomMaterial, Exercise, ExerciseHistory, GermanLevel, GrammarMastery, Mistake, PlacementResult, ReviewState, SyncState, UserProfile, UserProgress, WritingAttempt } from '../types'
import { scheduleReview, scheduleReviewGrade, type ReviewGrade } from '../engine/srs'
import { indexedDBStorage } from './db'

const today=()=>new Date().toISOString().slice(0,10)
const defaultProfile:UserProfile={name:'Leart',currentLevel:'A1',targetLevel:'B2',dailyGoal:30,goal:'Call center',weakAreas:['Grammatik','Sprechen'],strongAreas:['Wortschatz'],showTranslations:true,speechRate:.9,theme:'light',onboarded:false}
const defaultProgress:UserProgress={xp:0,streak:0,lessonsCompleted:[],exercisesCompleted:0,correctAnswers:0,speakingMinutes:0,grammarScore:0,listeningScore:0,levelProgress:{A1:0,A2:0,B1:0,B2:0},daily:{minutes:30,completedMinutes:0,date:today()}}
const defaultSync:SyncState={status:'local',message:'Progresi ruhet në këtë pajisje.'}
export type AppSnapshot={profile:UserProfile;progress:UserProgress;reviews:ReviewState[];mistakes:Mistake[];savedWords:string[];grammarMastery:GrammarMastery[];exerciseHistory:ExerciseHistory[];placementResult?:PlacementResult;writingAttempts:WritingAttempt[];customMaterials:CustomMaterial[]}
type State=AppSnapshot&{sync:SyncState;updateProfile:(p:Partial<UserProfile>)=>void;completeOnboarding:(level:GermanLevel,goal:string,minutes:number)=>void;completeLesson:(id:string,level:GermanLevel)=>void;recordExercise:(correct:boolean)=>void;recordExerciseDetailed:(exercise:Exercise,correct:boolean,answer:string,topicId?:string)=>void;recordSpeaking:(minutes:number)=>void;reviewWord:(id:string,correct:boolean)=>void;reviewWordGrade:(id:string,grade:ReviewGrade)=>void;toggleWord:(id:string)=>void;addMistake:(m:Omit<Mistake,'id'|'timestamp'|'reviewed'>)=>void;reviewMistake:(id:string)=>void;savePlacement:(result:PlacementResult)=>void;saveWriting:(attempt:WritingAttempt)=>void;addMaterial:(material:CustomMaterial)=>void;removeMaterial:(id:string)=>void;setSync:(sync:SyncState)=>void;reset:()=>void;importData:(data:Partial<AppSnapshot>)=>void}
export const useAppStore=create<State>()(persist((set,get)=>({
 profile:defaultProfile,progress:defaultProgress,reviews:[],mistakes:[],savedWords:[],grammarMastery:[],exerciseHistory:[],placementResult:undefined,writingAttempts:[],customMaterials:[],sync:defaultSync,
 updateProfile:p=>set(s=>({profile:{...s.profile,...p}})),
 completeOnboarding:(level,goal,minutes)=>set(s=>({profile:{...s.profile,currentLevel:level,goal,dailyGoal:minutes,onboarded:true},progress:{...s.progress,daily:{...s.progress.daily,minutes}}})),
 completeLesson:(id,level)=>set(s=>{if(s.progress.lessonsCompleted.includes(id))return s;const done=[...s.progress.lessonsCompleted,id];return{progress:{...s.progress,xp:s.progress.xp+25,lessonsCompleted:done,daily:{...s.progress.daily,completedMinutes:s.progress.daily.completedMinutes+10},levelProgress:{...s.progress.levelProgress,[level]:Math.min(100,s.progress.levelProgress[level]+4)}}}}),
 recordExercise:correct=>set(s=>({progress:{...s.progress,xp:s.progress.xp+(correct?10:2),exercisesCompleted:s.progress.exercisesCompleted+1,correctAnswers:s.progress.correctAnswers+(correct?1:0),daily:{...s.progress.daily,completedMinutes:s.progress.daily.completedMinutes+2}}})),
 recordExerciseDetailed:(exercise,correct,answer,topicId)=>set(s=>{const old=topicId?s.grammarMastery.find(m=>m.topicId===topicId):undefined;const attempts=(old?.attempts??0)+1;const correctCount=(old?.correct??0)+(correct?1:0);const score=Math.round(correctCount/attempts*100);const mastery:GrammarMastery|undefined=topicId?{topicId,attempts,correct:correctCount,score,status:attempts<3?'new':score>=80?'strong':'learning',lastPracticed:Date.now()}:undefined;const mistake: Mistake|undefined=!correct?{id:crypto.randomUUID(),original:answer||exercise.prompt,correction:exercise.answer,topic:topicId??exercise.skill,level:exercise.level,timestamp:Date.now(),reviewed:false}:undefined;return{progress:{...s.progress,xp:s.progress.xp+(correct?10:2),exercisesCompleted:s.progress.exercisesCompleted+1,correctAnswers:s.progress.correctAnswers+(correct?1:0),daily:{...s.progress.daily,completedMinutes:s.progress.daily.completedMinutes+2}},exerciseHistory:[{id:crypto.randomUUID(),exerciseId:exercise.id,topicId,skill:exercise.skill,correct,answer,timestamp:Date.now()},...s.exerciseHistory].slice(0,500),grammarMastery:mastery?[...s.grammarMastery.filter(m=>m.topicId!==topicId),mastery]:s.grammarMastery,mistakes:mistake?[mistake,...s.mistakes].slice(0,200):s.mistakes}}),
 recordSpeaking:minutes=>set(s=>({progress:{...s.progress,xp:s.progress.xp+Math.round(minutes*8),speakingMinutes:s.progress.speakingMinutes+minutes,daily:{...s.progress.daily,completedMinutes:s.progress.daily.completedMinutes+minutes}}})),
 reviewWord:(id,correct)=>set(s=>{const old=s.reviews.find(r=>r.wordId===id);const next={...scheduleReview(old,correct),wordId:id};return{reviews:[...s.reviews.filter(r=>r.wordId!==id),next],progress:{...s.progress,xp:s.progress.xp+(correct?5:1)}}}),
 reviewWordGrade:(id,grade)=>set(s=>{const old=s.reviews.find(r=>r.wordId===id);const next={...scheduleReviewGrade(old,grade),wordId:id};return{reviews:[...s.reviews.filter(r=>r.wordId!==id),next],progress:{...s.progress,xp:s.progress.xp+(grade==='again'?1:grade==='hard'?3:grade==='good'?5:7)}}}),
 toggleWord:id=>set(s=>({savedWords:s.savedWords.includes(id)?s.savedWords.filter(x=>x!==id):[...s.savedWords,id]})),
 addMistake:m=>set(s=>({mistakes:[{...m,id:crypto.randomUUID(),timestamp:Date.now(),reviewed:false},...s.mistakes].slice(0,100)})),
 reviewMistake:id=>set(s=>({mistakes:s.mistakes.map(m=>m.id===id?{...m,reviewed:true}:m)})),
 savePlacement:result=>set(s=>({placementResult:result,profile:{...s.profile,currentLevel:result.level},progress:{...s.progress,xp:s.progress.xp+50}})),
 saveWriting:attempt=>set(s=>({writingAttempts:[attempt,...s.writingAttempts].slice(0,100),progress:{...s.progress,xp:s.progress.xp+15,daily:{...s.progress.daily,completedMinutes:s.progress.daily.completedMinutes+8}}})),
 addMaterial:material=>set(s=>({customMaterials:[material,...s.customMaterials].slice(0,30)})),
 removeMaterial:id=>set(s=>({customMaterials:s.customMaterials.filter(m=>m.id!==id)})),
 setSync:sync=>set({sync}),
 reset:()=>set({profile:defaultProfile,progress:defaultProgress,reviews:[],mistakes:[],savedWords:[],grammarMastery:[],exerciseHistory:[],placementResult:undefined,writingAttempts:[],customMaterials:[],sync:defaultSync}),
 importData:data=>set(s=>({profile:data.profile??s.profile,progress:data.progress??s.progress,reviews:data.reviews??s.reviews,mistakes:data.mistakes??s.mistakes,savedWords:data.savedWords??s.savedWords,grammarMastery:data.grammarMastery??s.grammarMastery,exerciseHistory:data.exerciseHistory??s.exerciseHistory,placementResult:data.placementResult??s.placementResult,writingAttempts:data.writingAttempts??s.writingAttempts,customMaterials:data.customMaterials??s.customMaterials}))
}),{name:'deutschcoach-v1',version:2,storage:createJSONStorage(()=>indexedDBStorage),merge:(persisted,current)=>{const old=(persisted??{}) as Partial<State>;return{...current,...old,profile:{...current.profile,...old.profile},progress:{...current.progress,...old.progress,levelProgress:{...current.progress.levelProgress,...old.progress?.levelProgress},daily:{...current.progress.daily,...old.progress?.daily}},reviews:old.reviews??[],mistakes:old.mistakes??[],savedWords:old.savedWords??[],grammarMastery:old.grammarMastery??[],exerciseHistory:old.exerciseHistory??[],writingAttempts:old.writingAttempts??[],customMaterials:old.customMaterials??[],sync:old.sync??defaultSync}}}))
export const getProgressSnapshot=():AppSnapshot=>{const s=useAppStore.getState();return{profile:s.profile,progress:s.progress,reviews:s.reviews,mistakes:s.mistakes,savedWords:s.savedWords,grammarMastery:s.grammarMastery,exerciseHistory:s.exerciseHistory,placementResult:s.placementResult,writingAttempts:s.writingAttempts,customMaterials:s.customMaterials}}
export const exportProgress=()=>JSON.stringify({version:2,exportedAt:new Date().toISOString(),...getProgressSnapshot()},null,2)
