import { useState } from 'react'
import { AlertTriangle, ArrowRight, BookOpen, Check, Clock3, Languages, Lightbulb, Sparkles } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { AudioButton, Card, LevelBadge, ProgressBar } from '../components/ui'
import { LearningHelp } from '../components/LearningHelp'
import { grammarTopics } from '../data/content'
import { useAppStore } from '../store/useAppStore'
import type { GermanLevel } from '../types'

export default function Grammar(){const current=useAppStore(s=>s.profile.currentLevel);const preferred=useAppStore(s=>s.profile.showTranslations);const mastery=useAppStore(s=>s.grammarMastery);const [params]=useSearchParams();const requested=grammarTopics.find(g=>g.id===params.get('topic'));const [level,setLevel]=useState<GermanLevel>(requested?.level??current);const [open,setOpen]=useState(requested?.id??grammarTopics.find(g=>g.level===current)?.id);const [showSq,setShowSq]=useState(preferred);const topics=grammarTopics.filter(g=>g.level===level)
 return <div className="page"><div className="page-heading"><span className="eyebrow">GRAMMATIK, DIE FUNKTIONIERT</span><h1>Regeln verstehen. Sicher sprechen.</h1><p>{grammarTopics.length} tema me shpjegime, formula, gabime tipike dhe progres personal.</p><Link className="mastery-link" to="/mastery">Shiko hartën time të gramatikës <ArrowRight/></Link></div><LearningHelp area="grammar"/><div className="grammar-toolbar"><div className="level-tabs compact">{(['A1','A2','B1','B2'] as GermanLevel[]).map(l=><button className={level===l?'active':''} onClick={()=>{setLevel(l);setOpen(grammarTopics.find(g=>g.level===l)?.id)}} key={l}><b>{l}</b></button>)}</div><button className={`translation-toggle ${showSq?'active':''}`} onClick={()=>setShowSq(!showSq)}><Languages/>{showSq?'Shqip aktiv':'Shfaq shqip'}</button></div><div className="grammar-layout"><aside>{topics.map((g,i)=>{const m=mastery.find(x=>x.topicId===g.id);return <button className={open===g.id?'active':''} onClick={()=>setOpen(g.id)} key={g.id}><span>{m?.status==='strong'?<Check/>:i+1}</span>{g.title}<ArrowRight/></button>})}</aside><div>{topics.filter(g=>g.id===open).map(g=>{const m=mastery.find(x=>x.topicId===g.id);return <Card className="grammar-detail" key={g.id}><div className="grammar-title"><LevelBadge level={g.level}/><small><Clock3/> 5–8 min · {m?`${m.score}% mastery`:'E re'}</small></div><ProgressBar value={m?.score??0}/><h2>{g.title}</h2><p>{g.de}</p>{showSq&&<p className="sq-copy"><Languages/>{g.sq}</p>}<div className="when-box"><Lightbulb/><div><small>WANN BRAUCHE ICH DAS? · KUR PËRDORET?</small><strong>{g.when}</strong></div></div><div className="rule-box"><Sparkles/><div><small>FORMEL · FORMULA</small><strong>{g.formula}</strong><span>{g.rule}</span></div></div><h3><BookOpen/> Beispiele · Shembuj</h3>{g.examples.map(e=><div className="grammar-example" key={e.de}><div><strong>{e.de}</strong>{showSq&&<span>{e.sq}</span>}</div><AudioButton text={e.de} label=""/></div>)}<div className="grammar-tips"><strong><Lightbulb/> Schnell merken · Mbaje mend</strong>{g.tips?.map(t=><p key={t}><Check/>{t}</p>)}</div><div className="mistake-box"><AlertTriangle/><div><small>HÄUFIGER FEHLER · GABIM TIPIK</small><strong>{g.mistake}</strong></div></div><Link to="/practice" className="inline-cta">Mit Übungen festigen <Check/></Link></Card>})}</div></div></div>}
