import { useState } from 'react'
import { AlertTriangle, ArrowRight, BookOpen, Check, Sparkles } from 'lucide-react'
import { AudioButton, Card, LevelBadge } from '../components/ui'
import { grammarTopics } from '../data/content'
import { useAppStore } from '../store/useAppStore'
import type { GermanLevel } from '../types'

export default function Grammar(){const current=useAppStore(s=>s.profile.currentLevel);const [level,setLevel]=useState<GermanLevel>(current);const [open,setOpen]=useState(grammarTopics.find(g=>g.level===current)?.id);const topics=grammarTopics.filter(g=>g.level===level)
 return <div className="page"><div className="page-heading"><span className="eyebrow">GRAMMATIK, DIE FUNKTIONIERT</span><h1>Regeln verstehen. Sicher sprechen.</h1><p>Shpjegime të qarta në gjermanisht dhe shqip — gjithmonë me shembuj praktikë.</p></div><div className="level-tabs compact">{(['A1','A2','B1','B2'] as GermanLevel[]).map(l=><button className={level===l?'active':''} onClick={()=>{setLevel(l);setOpen(grammarTopics.find(g=>g.level===l)?.id)}} key={l}><b>{l}</b></button>)}</div><div className="grammar-layout"><aside>{topics.map((g,i)=><button className={open===g.id?'active':''} onClick={()=>setOpen(g.id)} key={g.id}><span>{i+1}</span>{g.title}<ArrowRight/></button>)}</aside><div>{topics.filter(g=>g.id===open).map(g=><Card className="grammar-detail" key={g.id}><LevelBadge level={g.level}/><h2>{g.title}</h2><p>{g.de}</p><p className="sq-copy">{g.sq}</p><div className="rule-box"><Sparkles/><div><small>REGEL · RREGULLI</small><strong>{g.rule}</strong></div></div><h3><BookOpen/> Beispiele</h3>{g.examples.map(e=><div className="grammar-example" key={e.de}><div><strong>{e.de}</strong><span>{e.sq}</span></div><AudioButton text={e.de} label=""/></div>)}<div className="mistake-box"><AlertTriangle/><div><small>HÄUFIGER FEHLER</small><strong>{g.mistake}</strong></div></div><button className="inline-cta">Mit Übungen festigen <Check/></button></Card>)}</div></div></div>}
