import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, Flame, Headphones, Mic2, Play, RotateCcw, Sparkles, Target } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Button, Card, ProgressBar, StatCard, Streak } from '../components/ui'
import { lessons } from '../data/content'
import { useAppStore } from '../store/useAppStore'

export default function Home(){const nav=useNavigate();const {profile,progress,reviews}=useAppStore();const pct=Math.round(progress.daily.completedMinutes/profile.dailyGoal*100);const next=lessons.find(l=>l.level===profile.currentLevel&&!progress.lessonsCompleted.includes(l.id))??lessons[0];const due=reviews.filter(r=>r.nextReview<=Date.now()).length||12
 return <div className="page home-page"><div className="page-heading home-heading"><div><span className="date-label"><CalendarDays/> HEUTE · {new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase()}</span><h1>Guten Tag, {profile.name}! <span>👋</span></h1><p>Heute zählt nicht Perfektion. Heute zählt, dass du sprichst.</p></div><Streak days={progress.streak||7}/></div>
 <Card className="daily-plan"><div className="plan-head"><div><span className="eyebrow">DEIN TAGESZIEL</span><h2>{profile.dailyGoal-progress.daily.completedMinutes>0?`Noch ${profile.dailyGoal-progress.daily.completedMinutes} Minuten`:'Tagesziel geschafft!'}</h2><p>Ein kurzer, ausgewogener Plan für echten Fortschritt.</p></div><div className="goal-ring" style={{'--pct':`${Math.min(100,pct)}%`} as React.CSSProperties}><strong>{Math.min(100,pct)}%</strong><span>{progress.daily.completedMinutes}/{profile.dailyGoal} min</span></div></div>
 <div className="session-list"><button onClick={()=>nav('/vocabulary')}><span className="session-icon orange"><BookOpen/></span><span><b>Wortschatz</b><small>12 fjalë · Call Center</small></span><em>5 MIN</em><ArrowRight/></button><button onClick={()=>nav('/practice')}><span className="session-icon yellow"><Sparkles/></span><span><b>Grammatik</b><small>Verbposition · 5 Übungen</small></span><em>10 MIN</em><ArrowRight/></button><button onClick={()=>nav('/listening')}><span className="session-icon blue"><Headphones/></span><span><b>Hören</b><small>Kundengespräch</small></span><em>5 MIN</em><ArrowRight/></button><button className="focus-session" onClick={()=>nav('/speaking')}><span className="session-icon green"><Mic2/></span><span><b>Sprechen</b><small>Problem mit der Rechnung</small></span><em>10 MIN</em><Play/></button></div></Card>
 <div className="home-grid"><Card className="continue-card"><span className="eyebrow">WEITERLERNEN</span><div className="lesson-visual"><span>{next.module.toString().padStart(2,'0')}</span><Sparkles/></div><div><span className="module-label">{next.level} · MODUL {next.module}</span><h3>{next.title}</h3><p>{next.subtitle}</p><ProgressBar value={35}/><small>3 von 8 Lektionen</small><Button onClick={()=>nav(`/lesson/${next.id}`)}>Fortsetzen <ArrowRight/></Button></div></Card>
 <div className="side-stack"><Card className="review-card"><div className="review-icon"><RotateCcw/></div><div><span className="eyebrow">WIEDERHOLEN</span><h3>{due} Wörter warten</h3><p>5 davon sind schwierig</p></div><button onClick={()=>nav('/vocabulary')}>Jetzt üben <ArrowRight/></button></Card><Card className="motivation"><Target/><div><strong>Dein Fokus heute</strong><p>Du wolltest mehr sprechen. Deshalb ist die Sprechübung heute doppelt gewichtet.</p></div></Card></div></div>
 <div className="stats-row"><StatCard icon={<Flame/>} value={progress.streak||7} label="Tage Streak" tone="coral"/><StatCard icon={<CheckCircle2/>} value={progress.lessonsCompleted.length} label="Lektionen"/><StatCard icon={<Mic2/>} value={`${progress.speakingMinutes} min`} label="Gesprochen" tone="blue"/><StatCard icon={<Sparkles/>} value={progress.xp} label="Gesamt-XP" tone="yellow"/></div></div>}
