import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, Flame, Headphones, Mic2, Play, RotateCcw, Sparkles, Target } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Button, Card, ProgressBar, StatCard, Streak } from '../components/ui'
import { lessons } from '../data/content'
import { useAppStore } from '../store/useAppStore'
import { buildDailyPlan, weakestGrammar } from '../engine/personalization'

export default function Home(){const nav=useNavigate();const state=useAppStore();const {profile,progress,reviews,mistakes}=state;const pct=Math.round(progress.daily.completedMinutes/profile.dailyGoal*100);const next=lessons.find(l=>l.level===profile.currentLevel&&!progress.lessonsCompleted.includes(l.id))??lessons[0];const due=reviews.filter(r=>r.nextReview<=Date.now()).length||10;const plan=buildDailyPlan(state);const weak=weakestGrammar(state)
 return <div className="page home-page"><div className="page-heading home-heading"><div><span className="date-label"><CalendarDays/> HEUTE · {new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase()}</span><h1>Guten Tag, {profile.name}! <span>👋</span></h1><p>Heute zählt nicht Perfektion. Heute zählt, dass du sprichst.</p></div><Streak days={progress.streak||7}/></div>
 <Card className="daily-plan"><div className="plan-head"><div><span className="eyebrow">DEIN TAGESZIEL</span><h2>{profile.dailyGoal-progress.daily.completedMinutes>0?`Noch ${profile.dailyGoal-progress.daily.completedMinutes} Minuten`:'Tagesziel geschafft!'}</h2><p>Ein kurzer, ausgewogener Plan für echten Fortschritt.</p></div><div className="goal-ring" style={{'--pct':`${Math.min(100,pct)}%`} as React.CSSProperties}><strong>{Math.min(100,pct)}%</strong><span>{progress.daily.completedMinutes}/{profile.dailyGoal} min</span></div></div>
 <div className="session-list">{plan.map((task,i)=>{const Icon=task.skill==='Wortschatz'?BookOpen:task.skill==='Grammatik'?Sparkles:task.skill==='Hören'?Headphones:task.skill==='Sprechen'?Mic2:BookOpen;return <button key={task.id} className={i===plan.length-1?'focus-session':''} onClick={()=>nav(task.route)} title={task.reason}><span className={`session-icon ${['orange','yellow','blue','green'][i]}`}><Icon/></span><span><b>{task.title}</b><small>{task.subtitle}</small><small className="plan-reason">{task.reason}</small></span><em>{task.minutes} MIN</em>{i===plan.length-1?<Play/>:<ArrowRight/>}</button>})}</div></Card>
 <div className="home-grid"><Card className="continue-card"><span className="eyebrow">WEITERLERNEN</span><div className="lesson-visual"><span>{next.module.toString().padStart(2,'0')}</span><Sparkles/></div><div><span className="module-label">{next.level} · MODUL {next.module}</span><h3>{next.title}</h3><p>{next.subtitle}</p><ProgressBar value={35}/><small>3 von 8 Lektionen</small><Button onClick={()=>nav(`/lesson/${next.id}`)}>Fortsetzen <ArrowRight/></Button></div></Card>
 <div className="side-stack"><Card className="review-card"><div className="review-icon"><RotateCcw/></div><div><span className="eyebrow">WIEDERHOLEN</span><h3>{due} Wörter warten</h3><p>{mistakes.filter(m=>!m.reviewed).length} gabime personale të hapura</p></div><button onClick={()=>nav('/flashcards')}>Jetzt üben <ArrowRight/></button></Card><Card className="motivation"><Target/><div><strong>Warum dieser Plan?</strong><p>Qëllimi: {profile.goal}. Gramatika për fokus: {weak?.title??'bazat e nivelit'}. Plani ndryshon me gabimet e tua.</p></div></Card></div></div>
 <div className="stats-row"><StatCard icon={<Flame/>} value={progress.streak||7} label="Tage Streak" tone="coral"/><StatCard icon={<CheckCircle2/>} value={progress.lessonsCompleted.length} label="Lektionen"/><StatCard icon={<Mic2/>} value={`${progress.speakingMinutes} min`} label="Gesprochen" tone="blue"/><StatCard icon={<Sparkles/>} value={progress.xp} label="Gesamt-XP" tone="yellow"/></div></div>}
