import { ArrowRight, BookOpen, Check, Clock3, Headphones, Lock, Mic2, Sparkles } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useState } from 'react'
import { Button, Card, LevelBadge, ProgressBar } from '../components/ui'
import { lessons, levelMeta } from '../data/content'
import { useAppStore } from '../store/useAppStore'
import type { GermanLevel } from '../types'

export function Learn(){const current=useAppStore(s=>s.profile.currentLevel);const [level,setLevel]=useState<GermanLevel>(current);const progress=useAppStore(s=>s.progress);const filtered=lessons.filter(l=>l.level===level)
 return <div className="page"><div className="page-heading"><span className="eyebrow">DEIN DEUTSCHKURS</span><h1>Lernen mit einem klaren Weg.</h1><p>Vom ersten Satz bis zum professionellen Kundengespräch.</p></div><div className="level-tabs">{(['A1','A2','B1','B2'] as GermanLevel[]).map(l=><button key={l} className={level===l?'active':''} onClick={()=>setLevel(l)}><b>{l}</b><span>{levelMeta[l].label}</span></button>)}</div><div className="level-summary"><div><LevelBadge level={level}/><h2>{levelMeta[level].description}</h2><p>{filtered.length} Module · Praktische Übungen · Sprechtraining</p></div><div><strong>{progress.levelProgress[level]}%</strong><ProgressBar value={progress.levelProgress[level]} color={levelMeta[level].color}/></div></div><div className="module-list">{filtered.map((l,i)=>{const done=progress.lessonsCompleted.includes(l.id);const accessible=i===0||progress.lessonsCompleted.includes(filtered[i-1].id)||true;const Icon=l.skill==='Sprechen'?Mic2:l.skill==='Hören'?Headphones:l.skill==='Grammatik'?Sparkles:BookOpen;return <Link key={l.id} to={`/lesson/${l.id}`} className={`module-card ${done?'done':''}`}><span className="module-number">{done?<Check/>:(i+1).toString().padStart(2,'0')}</span><span className="module-icon"><Icon/></span><span className="module-copy"><small>MODUL {i+1} · {l.skill.toUpperCase()}</small><b>{l.title}</b><em><Clock3/> {l.duration} min · 1 Lektion</em></span>{accessible?<ArrowRight/>:<Lock/>}</Link>})}</div></div>}
export function LessonPage(){const {id}=useParams();const nav=useNavigate();const lesson=lessons.find(l=>l.id===id);const complete=useAppStore(s=>s.completeLesson);const [step,setStep]=useState(0);if(!lesson)return <div className="page"><h1>Lektion nicht gefunden</h1></div>;const finish=()=>{complete(lesson.id,lesson.level);nav('/practice')}
 return <div className="page lesson-page"><Link to="/learn" className="back-link">← Kursübersicht</Link><div className="lesson-top"><LevelBadge level={lesson.level}/><span>MODUL {lesson.module}</span><h1>{lesson.title}</h1><p>{lesson.subtitle}</p></div><ProgressBar value={(step+1)/3*100}/><Card className="lesson-content">{step===0&&<><span className="eyebrow">VERSTEHEN</span><h2>Die Idee</h2>{lesson.content.map(x=><p key={x}>{x}</p>)}<div className="grammar-box"><Sparkles/><p><strong>Merke:</strong> Sprich jeden Beispielsatz mindestens zweimal laut. Dein Mund muss Deutsch genauso lernen wie dein Kopf.</p></div></>}{step===1&&<><span className="eyebrow">BEISPIEL</span><h2>Deutsch im echten Leben</h2>{lesson.examples.map(e=><div className="example-block" key={e.de}><strong>{e.de}</strong><span>{e.sq}</span></div>)}</>}{step===2&&<><span className="eyebrow">AKTIV WERDEN</span><h2>Jetzt du.</h2><p>Sprich den Beispielsatz laut. Achte auf einen ruhigen Rhythmus und vollständige Wörter.</p><div className="speak-preview"><Mic2/><strong>{lesson.examples[0].de}</strong><span>Tippe auf „Übung starten”, um deine Antwort zu prüfen.</span></div></>}<div className="lesson-actions">{step>0&&<Button variant="ghost" onClick={()=>setStep(step-1)}>Zurück</Button>}<Button onClick={()=>step<2?setStep(step+1):finish()}>{step<2?'Weiter':'Übung starten'} <ArrowRight/></Button></div></Card></div>}
