import { useState } from 'react'
import { Check, Headphones, Play, RotateCcw } from 'lucide-react'
import { Button, Card } from '../components/ui'
import { speakGerman } from '../engine/coach'
import { LearningHelp } from '../components/LearningHelp'
const items=[
 {text:'Guten Tag. Könnten Sie mir bitte Ihre Kundennummer nennen?',q:'Çfarë kërkon agjenti?',options:['Numrin e klientit','Adresën','Një pagesë'],answer:0,note:'„nennen” këtu do të thotë: ta thuash.'},
 {text:'Ich überprüfe Ihre Rechnung. Einen Moment bitte.',q:'Çfarë po kontrollon agjenti?',options:['Internetin','Faturën','Terminin'],answer:1,note:'überprüfen = kontrolloj me kujdes.'},
 {text:'Der Techniker kann morgen zwischen zehn und zwölf Uhr kommen.',q:'Kur mund të vijë tekniku?',options:['Sot në 12','Nesër 10–12','Të hënën'],answer:1,note:'zwischen … und … = ndërmjet … dhe …'},
 {text:'Leider ist der gewünschte Artikel momentan nicht lieferbar.',q:'Cili është problemi?',options:['Produkti nuk mund të dorëzohet tani','Produkti është shumë i shtrenjtë','Porosia është anuluar'],answer:0,note:'lieferbar = i disponueshëm për dorëzim.'},
 {text:'Wenn Sie möchten, kann ich Ihnen einen Ersatztermin am Freitag anbieten.',q:'Çfarë ofron folësi?',options:['Rimbursim','Një takim tjetër të premten','Një telefonatë sot'],answer:1,note:'Ersatztermin = një orar alternativ.'},
 {text:'Obwohl die Garantie bereits abgelaufen ist, prüfen wir eine Lösung aus Kulanz.',q:'Pse është oferta e veçantë?',options:['Garancia është ende aktive','Po bëhet nga mirëkuptimi tregtar','Pajisja është e re'],answer:1,note:'aus Kulanz = vullnetarisht, si gjest ndaj klientit.'},
 {text:'Ich fasse kurz zusammen: Sie erhalten morgen eine schriftliche Bestätigung und bis Freitag die Erstattung.',q:'Çfarë vjen nesër?',options:['Rimbursimi','Konfirmimi me shkrim','Pajisja'],answer:1,note:'zusammenfassen = përmbledh; Erstattung = rimbursim.'},
 {text:'Die Störung betrifft mehrere Haushalte. Unsere Techniker arbeiten bereits an der Behebung.',q:'Kë prek problemi?',options:['Vetëm një klient','Disa familje','Vetëm teknikët'],answer:1,note:'Behebung = zgjidhja/rregullimi i një defekti.'},
]
export default function Listening(){const [i,setI]=useState(0);const [answer,setAnswer]=useState<number|null>(null);const item=items[i];return <div className="page listening-page"><div className="page-heading"><span className="eyebrow">HÖRVERSTEHEN</span><h1>Hör genau hin.</h1><p>{items.length} situata reale me ritëm normal, përsëritje të ngadaltë dhe shpjegim.</p></div><LearningHelp area="listening"/><Card className="listening-card"><div className="listen-orb"><Headphones/></div><span>AUFGABE {i+1} VON {items.length}</span><h2>Kundengespräch</h2><button className="play-audio" onClick={()=>speakGerman(item.text,.85)}><Play/> Audio abspielen</button><h3>{item.q}</h3><div className="answer-options">{item.options.map((o,oi)=><button key={o} onClick={()=>answer===null&&setAnswer(oi)} className={`${answer===oi?'selected':''} ${answer!==null&&oi===item.answer?'correct':''}`}><span>{String.fromCharCode(65+oi)}</span>{o}{answer!==null&&oi===item.answer&&<Check/>}</button>)}</div>{answer!==null&&<div className={`feedback ${answer===item.answer?'good':'bad'}`}><Check/><div><strong>{answer===item.answer?'Richtig!':'Richtige Antwort markiert.'}</strong><p>„{item.text}”</p><p><b>Ndihmë:</b> {item.note}</p></div></div>}<Button onClick={()=>{setI((i+1)%items.length);setAnswer(null)}} disabled={answer===null}>Weiter</Button><button className="repeat" onClick={()=>speakGerman(item.text,.7)}><RotateCcw/> Langsamer hören</button></Card></div>}
