import { useMemo, useRef, useState } from 'react'
import { AlertTriangle, BarChart3, BookOpen, BriefcaseBusiness, CheckCircle2, Download, FileText, Flame, Gauge, Headphones, Import, Languages, Moon, RotateCcw, Search, Settings as SettingsIcon, Sparkles, Sun, Target, Upload } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { AudioButton, Button, Card, LevelBadge, ProgressBar, StatCard } from '../components/ui'
import { conversations, grammarTopics, lessons, phrases, vocabulary } from '../data/content'
import { exportProgress, useAppStore } from '../store/useAppStore'
import type { GermanLevel } from '../types'

export function Progress(){const {profile,progress,mistakes,reviews}=useAppStore();const accuracy=progress.exercisesCompleted?Math.round(progress.correctAnswers/progress.exercisesCompleted*100):0;return <div className="page"><div className="page-heading progress-heading"><div><span className="eyebrow">DEIN FORTSCHRITT</span><h1>Jede Übung zählt.</h1><p>Deine Daten bleiben lokal auf diesem Gerät.</p></div><div className="xp-pill"><Sparkles/>{progress.xp} XP</div></div><div className="stats-row"><StatCard icon={<Flame/>} value={progress.streak||7} label="Tage Streak" tone="coral"/><StatCard icon={<BookOpen/>} value={progress.lessonsCompleted.length} label="Lektionen"/><StatCard icon={<Gauge/>} value={`${accuracy}%`} label="Genauigkeit" tone="blue"/><StatCard icon={<Headphones/>} value={`${progress.speakingMinutes} min`} label="Gesprochen" tone="yellow"/></div><div className="progress-layout"><Card className="level-progress"><span className="eyebrow">CEFR LERNPFAD</span><h2>Von {profile.currentLevel} bis {profile.targetLevel}</h2>{(['A1','A2','B1','B2'] as GermanLevel[]).map(l=><div className="level-row" key={l}><LevelBadge level={l}/><div><strong>{l==='A1'?'Grundlagen':l==='A2'?'Alltag & Arbeit':l==='B1'?'Selbstständig sprechen':'Professionell kommunizieren'}</strong><ProgressBar value={progress.levelProgress[l]}/></div><b>{progress.levelProgress[l]}%</b></div>)}</Card><Card className="weekly-chart"><span className="eyebrow">DIESE WOCHE</span><h2>Lernaktivität</h2><div className="bars">{[18,30,12,26,34,8,progress.daily.completedMinutes].map((v,i)=><div key={i}><span style={{height:`${Math.max(8,v*2)}px`}}/><small>{['Mo','Di','Mi','Do','Fr','Sa','So'][i]}</small></div>)}</div><div className="chart-note"><Target/><span><strong>{126+progress.daily.completedMinutes} Minuten</strong>dieser Woche gelernt</span></div></Card></div><Card className="mistakes"><div className="section-title"><div><span className="eyebrow">MEINE FEHLER</span><h2>Aus Fehlern wird Sicherheit.</h2></div><span>{mistakes.length} gespeichert</span></div>{mistakes.length?mistakes.slice(0,5).map(m=><div className="mistake-row" key={m.id}><AlertTriangle/><div><del>{m.original}</del><strong>{m.correction}</strong><small>{m.topic} · {m.level}</small></div></div>):<div className="empty-state"><CheckCircle2/><strong>Noch keine Fehler gespeichert</strong><span>Fehler aus Sprechübungen erscheinen automatisch hier.</span></div>}<div className="review-summary"><RotateCcw/><span><b>{reviews.filter(r=>r.nextReview<=Date.now()).length}</b> Wörter heute zur Wiederholung</span></div></Card></div>}

export function Settings(){const {profile,updateProfile,reset,importData}=useAppStore();const file=useRef<HTMLInputElement>(null);const download=()=>{const blob=new Blob([exportProgress()],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`deutschcoach-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)};const load=async(f:File)=>{try{importData(JSON.parse(await f.text()))}catch{alert('Kjo kopje rezervë nuk është e vlefshme.')}}
 return <div className="page settings-page"><div className="page-heading"><span className="eyebrow">EINSTELLUNGEN</span><h1>Dein DeutschCoach.</h1><p>Përshtate mënyrën si mëson dhe ruaj një kopje të progresit.</p></div><div className="settings-grid"><Card><h2><Languages/> Lernen</h2><label>Aktuelles Niveau<select value={profile.currentLevel} onChange={e=>updateProfile({currentLevel:e.target.value as GermanLevel})}>{['A1','A2','B1','B2'].map(l=><option key={l}>{l}</option>)}</select></label><label>Tagesziel<select value={profile.dailyGoal} onChange={e=>updateProfile({dailyGoal:+e.target.value})}>{[15,30,45,60].map(m=><option value={m} key={m}>{m} Minuten</option>)}</select></label><label className="switch-row">Përkthimet në shqip<input type="checkbox" checked={profile.showTranslations} onChange={e=>updateProfile({showTranslations:e.target.checked})}/></label></Card><Card><h2><SettingsIcon/> Sprache & Ton</h2><label>Sprechgeschwindigkeit<input type="range" min="0.6" max="1.2" step="0.1" value={profile.speechRate} onChange={e=>updateProfile({speechRate:+e.target.value})}/><span>{profile.speechRate}×</span></label><label>Darstellung<div className="theme-picker"><button className={profile.theme==='light'?'active':''} onClick={()=>updateProfile({theme:'light'})}><Sun/> Hell</button><button className={profile.theme==='dark'?'active':''} onClick={()=>updateProfile({theme:'dark'})}><Moon/> Dunkel</button></div></label><p className="privacy-copy">SpeechRecognition mund të përpunohet nga shfletuesi ose sistemi operativ dhe ndryshon sipas pajisjes. DeutschCoach nuk dërgon të dhëna te një server i vet.</p></Card><Card><h2><Download/> Të dhënat</h2><p>Eksporto një kopje JSON për ta transferuar progresin në një pajisje tjetër.</p><div className="data-actions"><Button onClick={download}><Download/> Eksporto</Button><Button variant="secondary" onClick={()=>file.current?.click()}><Upload/> Importo</Button><input ref={file} hidden type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&load(e.target.files[0])}/></div><button className="danger-link" onClick={()=>confirm('Të fshihet i gjithë progresi lokal?')&&reset()}><RotateCcw/> Rivendos progresin</button></Card></div></div>}

export function SearchPage(){const [params]=useSearchParams();const [q,setQ]=useState(params.get('q')||'');const results=useMemo(()=>{const n=q.toLowerCase().trim();if(!n)return[];return [...vocabulary.filter(v=>`${v.word} ${v.translation} ${v.topic}`.toLowerCase().includes(n)).map(v=>({type:'Wort',title:`${v.article??''} ${v.word}`,text:v.translation,level:v.level})),...grammarTopics.filter(g=>`${g.title} ${g.de} ${g.sq}`.toLowerCase().includes(n)).map(g=>({type:'Grammatik',title:g.title,text:g.sq,level:g.level})),...lessons.filter(l=>`${l.title} ${l.subtitle}`.toLowerCase().includes(n)).map(l=>({type:'Lektion',title:l.title,text:l.subtitle,level:l.level})),...phrases.filter(p=>`${p.de} ${p.sq}`.toLowerCase().includes(n)).map(p=>({type:'Redemittel',title:p.de,text:p.sq,level:p.level})),...conversations.filter(c=>`${c.title} ${c.goal}`.toLowerCase().includes(n)).map(c=>({type:'Simulation',title:c.title,text:c.goal,level:c.level}))].slice(0,40)},[q]);return <div className="page"><div className="page-heading"><span className="eyebrow">ALLES FINDEN</span><h1>Suche</h1></div><div className="big-search"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechnung, Perfekt, Kundennummer…"/></div><p className="result-count">{results.length} rezultate për “{q}”</p><div className="search-results">{results.map((r,i)=><Card key={`${r.type}-${i}`}><LevelBadge level={r.level}/><span>{r.type}</span><h3>{r.title}</h3><p>{r.text}</p></Card>)}</div></div>}

export function Phrasebook(){const [q,setQ]=useState('');const shown=phrases.filter(p=>`${p.de} ${p.sq} ${p.category}`.toLowerCase().includes(q.toLowerCase()));return <div className="page"><div className="page-heading"><span className="eyebrow">REDEMITTEL</span><h1>Sätze für echte Gespräche.</h1></div><div className="big-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Fraza për punë, udhëtim, call center…"/></div><div className="phrase-list">{shown.map(p=><Card key={p.id}><LevelBadge level={p.level}/><small>{p.category}</small><h3>{p.de}</h3><p>{p.sq}</p><AudioButton text={p.de}/></Card>)}</div></div>}

export function Tests(){const levels=['A1','A2','B1','B2'] as GermanLevel[];return <div className="page"><div className="page-heading"><span className="eyebrow">PRÜFUNGSMODUS</span><h1>Prüfe, was du kannst.</h1><p>Vlerësim praktik, jo certifikim zyrtar CEFR.</p></div><div className="exam-grid">{levels.map(l=><Card key={l}><LevelBadge level={l}/><h2>{l} Probetest</h2><p>Lesen · Hören · Schreiben · Sprechen</p><div className="exam-skills">{['Lesen','Hören','Schreiben','Sprechen'].map(s=><span key={s}><CheckCircle2/>{s}</span>)}</div><Button onClick={()=>location.assign('/practice')}>Test starten</Button></Card>)}</div></div>}
