import { useState } from 'react'
import { ArrowRight, BriefcaseBusiness, Check, Globe2, GraduationCap, MessageCircle, Plane, Sparkles } from 'lucide-react'
import { useAppStore } from '../store/useAppStore'
import type { GermanLevel } from '../types'
import { Button } from '../components/ui'

export default function Onboarding(){const complete=useAppStore(s=>s.completeOnboarding);const [step,setStep]=useState(0);const [level,setLevel]=useState<GermanLevel>('A1');const [goal,setGoal]=useState('Call center');const [minutes,setMinutes]=useState(30)
 const goals=[['Everyday German','Gjermanishte për jetën e përditshme',Globe2],['Call center','Gjermanishte për call center',BriefcaseBusiness],['Reach B1/B2','Arrij nivelin B1/B2',MessageCircle],['Goethe/TELC','Përgatitje për Goethe/TELC',GraduationCap]] as const
 return <main className="onboarding"><div className="onboard-brand"><span className="brand-mark">D<span>•</span></span><strong>DeutschCoach</strong></div><div className="onboard-card"><div className="step-dots">{[0,1,2].map(i=><i key={i} className={i<=step?'active':''}/>)}</div>
 {step===0&&<><span className="eyebrow">SCHRITT 1 VON 3</span><h1>Sa gjermanisht di?</h1><p>Zgjidh nivelin tënd aktual. Mund ta ndryshosh kurdo.</p><div className="level-grid">{(['A1','A2','B1','B2'] as GermanLevel[]).map(l=><button key={l} onClick={()=>setLevel(l)} className={level===l?'selected':''}><b>{l}</b><span>{l==='A1'?'Jam fillestar':l==='A2'?'Di bazat':l==='B1'?'Flas në situata të zakonshme':'Komunikoj me siguri'}</span>{level===l&&<Check/>}</button>)}</div><button className="placement" onClick={()=>{complete('A1',goal,minutes);location.assign('/placement')}}>Nuk e di — bëj testin e plotë të nivelit</button></>}
 {step===1&&<><span className="eyebrow">SCHRITT 2 VON 3</span><h1>Cili është qëllimi yt?</h1><p>Plani i përditshëm do të ndryshojë sipas këtij qëllimi.</p><div className="goal-grid">{goals.map(([id,label,I])=><button key={id} onClick={()=>setGoal(id)} className={goal===id?'selected':''}><I/><span>{label}</span>{goal===id&&<Check/>}</button>)}</div></>}
 {step===2&&<><span className="eyebrow">SCHRITT 3 VON 3</span><h1>Sa kohë ke çdo ditë?</h1><p>30 minuta në ditë krijojnë përparim të qëndrueshëm.</p><div className="time-grid">{[15,30,45,60].map(m=><button key={m} onClick={()=>setMinutes(m)} className={minutes===m?'selected':''}><b>{m}{m===60?'＋':''}</b><span>minuta</span>{m===30&&<small>E REKOMANDUAR</small>}</button>)}</div><div className="coach-note"><Sparkles/><span><strong>Plan i fokusuar te të folurit</strong>Do të praktikosh gjermanishten reale për punë dhe call center.</span></div></>}
 <div className="onboard-actions">{step>0&&<Button variant="ghost" onClick={()=>setStep(step-1)}>Prapa</Button>}<Button onClick={()=>step<2?setStep(step+1):complete(level,goal,minutes)}>{step<2?'Vazhdo':'Fillo mësimin'} <ArrowRight/></Button></div></div><small className="privacy-note">Pa reklama · Pa API me pagesë · Lokalisht dhe me cloud privat opsional</small></main>}
