import { ArrowRight, BookOpenCheck, Check, Cloud, Eye, GraduationCap, Languages, Lightbulb, RefreshCw, RotateCcw, Sparkles, Trash2, Upload, Volume2, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { AudioButton, Button, Card, LevelBadge, ProgressBar } from '../components/ui'
import { exercises, grammarTopics, vocabulary } from '../data/content'
import { analyzeMaterial } from '../engine/importer'
import { normalizeText, validateAnswer } from '../engine/grammar'
import { useAppStore } from '../store/useAppStore'
import type { GermanLevel, Skill } from '../types'

const placementQuestions=[
 ['A1','Grammatik','Ich ___ Leart.',['heiße','heißt','heißen'],'heiße'],['A1','Wortschatz','___ Problem',['der','die','das'],'das'],['A1','Lesen','„Der Kurs beginnt um neun.” Wann beginnt er?',['Um acht','Um neun','Am Montag'],'Um neun'],['A1','Hören','Guten Tag. Ich hätte gern einen Kaffee, bitte.',['Die Person bestellt etwas.','Die Person kündigt.','Die Person ist krank.'],'Die Person bestellt etwas.'],
 ['A2','Grammatik','Ich ___ gestern lange gearbeitet.',['habe','bin','werde'],'habe'],['A2','Grammatik','Ich spreche ___ meiner Kollegin.',['mit','für','durch'],'mit'],['A2','Lesen','„Der Termin wurde auf Donnerstag verschoben.” Was ist neu?',['Der Ort','Der Tag','Die Person'],'Der Tag'],['A2','Hören','Der Zug hat zwanzig Minuten Verspätung.',['Der Zug kommt später.','Der Zug fällt aus.','Der Zug ist leer.'],'Der Zug kommt später.'],
 ['B1','Grammatik','Ich rufe an, weil ich Hilfe ___.',['brauche','brauchen','gebraucht'],'brauche'],['B1','Grammatik','Das ist die Kollegin, ___ mir geholfen hat.',['die','der','den'],'die'],['B1','Lesen','„Sollte die Lieferung nicht erfolgen, storniere ich.” Was ist die Bedingung?',['Keine Lieferung','Hohe Kosten','Eine Antwort'],'Keine Lieferung'],['B1','Hören','Ich fasse zusammen: Sie erhalten morgen eine Rückmeldung.',['Die Antwort kommt morgen.','Der Vertrag endet.','Die Rechnung fehlt.'],'Die Antwort kommt morgen.'],
 ['B2','Grammatik','Der Kunde sagt, er ___ keine Nachricht erhalten.',['habe','hat','würde'],'habe'],['B2','Grammatik','Das Problem lässt ___ schnell lösen.',['sich','ihm','es'],'sich'],['B2','Lesen','„Zwar ist die Lösung teuer, jedoch langfristig sinnvoll.” Welche Beziehung?',['Gegensatz','Ursache','Zeitfolge'],'Gegensatz'],['B2','Hören','Aus Kulanz erstatten wir die Gebühr vollständig.',['Die Erstattung ist ein freiwilliges Entgegenkommen.','Die Garantie gilt.','Der Kunde muss zahlen.'],'Die Erstattung ist ein freiwilliges Entgegenkommen.'],
] as const

export function PlacementTest(){const nav=useNavigate();const save=useAppStore(s=>s.savePlacement);const previous=useAppStore(s=>s.placementResult);const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<string[]>([]);const [production,setProduction]=useState(false);const [writing,setWriting]=useState('');const [speaking,setSpeaking]=useState('');const [finished,setFinished]=useState(false);const q=placementQuestions[index];const wordScore=(text:string)=>{const count=text.trim()?text.trim().split(/\s+/).length:0;const links=(text.match(/\b(weil|obwohl|deshalb|dass|wenn|trotzdem|einerseits|andererseits)\b/gi)??[]).length;return Math.min(100,count*4+links*10)};const finish=()=>{const correct=answers.filter((a,i)=>a===placementQuestions[i][4]).length;const objective=Math.round(correct/placementQuestions.length*100);const writingScore=wordScore(writing);const speakingScore=wordScore(speaking);const score=Math.round(objective*.7+(writingScore+speakingScore)/2*.3);const level:GermanLevel=score<45?'A1':score<65?'A2':score<82?'B1':'B2';const skills=['Grammatik','Wortschatz','Lesen','Hören'] as Skill[];const sectionScores=Object.fromEntries(skills.map(skill=>{const relevant=placementQuestions.map((x,i)=>({x,i})).filter(v=>v.x[1]===skill);return[skill,Math.round(relevant.filter(v=>answers[v.i]===v.x[4]).length/relevant.length*100)]})) as Partial<Record<Skill,number>>;const complete={...sectionScores,Sprechen:speakingScore,Schreiben:writingScore} as Record<Skill,number>;save({level,score,sectionScores:complete,completedAt:Date.now()});setFinished(true)};const choose=(answer:string)=>{const next=[...answers,answer];setAnswers(next);if(index===placementQuestions.length-1)setProduction(true);else setIndex(i=>i+1)};const restart=()=>{setIndex(0);setAnswers([]);setProduction(false);setWriting('');setSpeaking('');setFinished(false)}
 if(finished){const result=useAppStore.getState().placementResult!;return <div className="page placement-page"><Card className="placement-result"><span className="result-orb"><GraduationCap/></span><span className="eyebrow">DEIN ERGEBNIS</span><h1>Empfohlenes Niveau: {result.level}</h1><p>Rezultati yt është <b>{result.score}%</b>. Niveli i kursit u përshtat automatikisht.</p><div className="skill-results">{Object.entries(result.sectionScores).map(([skill,value])=><div key={skill}><span>{skill}</span><ProgressBar value={value}/><b>{value}%</b></div>)}</div><div className="result-actions"><Button onClick={()=>nav('/')}>Planin tim <ArrowRight/></Button><Button variant="secondary" onClick={restart}><RotateCcw/> Përsërit testin</Button></div></Card></div>}
 if(production)return <div className="page placement-page"><div className="page-heading"><span className="eyebrow">PRODUKTION · 2 VON 2</span><h1>Jetzt produzierst du selbst.</h1><p>Këto dy përgjigje matin sa të gjata dhe sa të lidhura janë fjalitë e tua. Nuk kërkohet perfeksion.</p></div><Card className="production-test"><label><b>Schreiben</b><span>Schreibe eine kurze E-Mail: Du kannst morgen nicht arbeiten. Erkläre warum und schlage eine Lösung vor.</span><textarea value={writing} onChange={e=>setWriting(e.target.value)} placeholder="Guten Tag, leider …"/></label><label><b>Sprechen</b><span>Was würdest du am Telefon sagen? Ein Kunde hat eine falsche Rechnung erhalten.</span><AudioButton text="Guten Tag. Ich habe eine falsche Rechnung erhalten. Können Sie mir helfen?" label="Situata"/><textarea value={speaking} onChange={e=>setSpeaking(e.target.value)} placeholder="Guten Tag. Ich kann Ihren Ärger …"/></label><Button onClick={finish} disabled={writing.trim().split(/\s+/).length<5||speaking.trim().split(/\s+/).length<5}>Ergebnis berechnen <ArrowRight/></Button></Card></div>
 return <div className="page placement-page"><div className="page-heading"><span className="eyebrow">EINSTUFUNGSTEST · 1 VON 2</span><h1>Finde deinen echten Startpunkt.</h1><p>16 pyetje A1–B2, pastaj një detyrë shkrimi dhe një përgjigje të folur. Rezultati përshtat kursin.</p>{previous&&<small>Testi i fundit: {previous.level} · {previous.score}%</small>}</div><div className="practice-progress"><span>Frage {index+1} von {placementQuestions.length}</span><ProgressBar value={(index+1)/placementQuestions.length*80}/></div><Card className="placement-question"><div><LevelBadge level={q[0]}/><span>{q[1]}</span></div>{q[1]==='Hören'&&<AudioButton text={q[2]} label="Audio hören"/>}<h2>{q[1]==='Hören'?'Dëgjo dhe zgjidh kuptimin:':q[2]}</h2><div className="answer-options">{q[3].map(option=><button key={option} onClick={()=>choose(option)}>{option}<ArrowRight/></button>)}</div></Card></div>}

export function Flashcards(){const level=useAppStore(s=>s.profile.currentLevel);const reviews=useAppStore(s=>s.reviews);const saved=useAppStore(s=>s.savedWords);const review=useAppStore(s=>s.reviewWord);const [direction,setDirection]=useState<'de-sq'|'sq-de'>('de-sq');const [index,setIndex]=useState(0);const [revealed,setRevealed]=useState(false);const due=reviews.filter(r=>r.nextReview<=Date.now()).map(r=>r.wordId);const cards=useMemo(()=>{const pool=vocabulary.filter(v=>v.level===level);return [...pool.filter(v=>due.includes(v.id)),...pool.filter(v=>saved.includes(v.id)&&!due.includes(v.id)),...pool.filter(v=>!saved.includes(v.id)&&!due.includes(v.id))].slice(0,30)},[level,due.join(','),saved.join(',')]);const card=cards[index%cards.length];const grade=(correct:boolean)=>{review(card.id,correct);setIndex(i=>i+1);setRevealed(false)}
 return <div className="page flashcard-page"><div className="page-heading"><span className="eyebrow">INTELLIGENTE WIEDERHOLUNG</span><h1>Fjalët që të duhen sot.</h1><p>Radha përshtatet sipas fjalëve të vështira, të ruajtura dhe afatit të përsëritjes.</p></div><div className="flash-toolbar"><div className="mini-tabs"><button className={direction==='de-sq'?'active':''} onClick={()=>{setDirection('de-sq');setRevealed(false)}}>DE → SQ</button><button className={direction==='sq-de'?'active':''} onClick={()=>{setDirection('sq-de');setRevealed(false)}}>SQ → DE</button></div><span>{index+1} / {cards.length}</span></div><Card className={`flashcard ${revealed?'revealed':''}`} onClick={()=>setRevealed(true)}><LevelBadge level={card.level}/><small>{card.topic}</small><h2>{direction==='de-sq'?`${card.article??''} ${card.word}`:card.translation}</h2>{direction==='de-sq'&&<AudioButton text={`${card.article??''} ${card.word}`} label="Dëgjo"/>}{revealed?<div className="flash-answer"><span>KUPTIMI</span><strong>{direction==='de-sq'?card.translation:`${card.article??''} ${card.word}`}</strong><p>{card.example}</p><AudioButton text={card.example} label="Shembulli"/></div>:<button className="reveal-button"><Eye/> Shfaq përgjigjen</button>}</Card>{revealed&&<div className="flash-grades"><button onClick={()=>grade(false)}><RotateCcw/><b>E vështirë</b><span>përsërite shpejt</span></button><button onClick={()=>grade(true)}><Check/><b>E dija</b><span>rrit intervalin</span></button></div>}</div>}

export function MistakeLab(){const mistakes=useAppStore(s=>s.mistakes);const review=useAppStore(s=>s.reviewMistake);const [index,setIndex]=useState(0);const [answer,setAnswer]=useState('');const [result,setResult]=useState<boolean|null>(null);const open=mistakes.filter(m=>!m.reviewed);const item=open[index%Math.max(open.length,1)];if(!item)return <div className="page"><div className="page-heading"><span className="eyebrow">FEHLERTRAINING</span><h1>Keine offenen Fehler.</h1><p>Shumë mirë. Gabimet e reja nga ushtrimet, shkrimi dhe të folurit do të shfaqen këtu.</p></div><Card className="empty-state"><Check/><strong>Alles wiederholt</strong><Link to="/practice">Bëj ushtrime të reja <ArrowRight/></Link></Card></div>;const check=()=>setResult(validateAnswer(answer,item.correction).correct);const next=()=>{if(result)review(item.id);setIndex(i=>i+1);setAnswer('');setResult(null)}
 return <div className="page"><div className="page-heading"><span className="eyebrow">MEINE FEHLER</span><h1>Aus deinem Fehler wird eine Übung.</h1><p>{open.length} gabime të hapura. Shkruaje formën e saktë pa e parë.</p></div><Card className="mistake-lab"><div><LevelBadge level={item.level}/><span>{item.topic}</span></div><small>DEINE FRÜHERE ANTWORT</small><h2>{item.original}</h2><textarea value={answer} onChange={e=>setAnswer(e.target.value)} disabled={result!==null} placeholder="Schreibe die richtige Form …"/>{result!==null&&<div className={`feedback ${result?'good':'bad'}`}>{result?<Check/>:<X/>}<div><strong>{result?'Richtig — dieser Fehler sitzt jetzt besser.':'Fast. Vergleiche Wort für Wort.'}</strong><p>Richtige Form: <b>{item.correction}</b></p></div></div>}<div className="exercise-actions">{result===null?<Button onClick={check} disabled={!answer.trim()}>Prüfen</Button>:<Button onClick={next}>{result?'Als gelernt markieren':'Später wiederholen'} <ArrowRight/></Button>}</div></Card></div>}

export function Mastery(){const mastery=useAppStore(s=>s.grammarMastery);const level=useAppStore(s=>s.profile.currentLevel);const topics=grammarTopics.filter(g=>g.level===level);return <div className="page"><div className="page-heading"><span className="eyebrow">GRAMMATIK-MASTERY</span><h1>Du siehst genau, was schon sitzt.</h1><p>Çdo temë kalon nga “E re” në “Në mësim” dhe pastaj “E fortë” sipas përgjigjeve të tua.</p></div><div className="mastery-summary"><Card><b>{topics.filter(g=>(mastery.find(m=>m.topicId===g.id)?.status??'new')==='strong').length}</b><span>tema të forta</span></Card><Card><b>{topics.filter(g=>(mastery.find(m=>m.topicId===g.id)?.status??'new')==='learning').length}</b><span>në mësim</span></Card><Card><b>{topics.filter(g=>!mastery.find(m=>m.topicId===g.id)).length}</b><span>të reja</span></Card></div><div className="mastery-list">{topics.map(g=>{const m=mastery.find(x=>x.topicId===g.id);const score=m?.score??0;return <Card key={g.id}><div><LevelBadge level={g.level}/><span className={`mastery-status ${m?.status??'new'}`}>{m?.status==='strong'?'E fortë':m?.status==='learning'?'Në mësim':'E re'}</span></div><h3>{g.title}</h3><p>{g.sq}</p><ProgressBar value={score}/><small>{m?`${m.correct}/${m.attempts} përgjigje të sakta`:'Ende pa ushtruar'}</small><div><Link to={`/grammar?topic=${g.id}`}>Shpjegimi</Link><Link to="/practice">Ushtro <ArrowRight/></Link></div></Card>})}</div></div>}

export function Importer(){const level=useAppStore(s=>s.profile.currentLevel);const materials=useAppStore(s=>s.customMaterials);const add=useAppStore(s=>s.addMaterial);const remove=useAppStore(s=>s.removeMaterial);const [active,setActive]=useState<GermanLevel>(level);const [title,setTitle]=useState('');const [text,setText]=useState('');const [created,setCreated]=useState<string>();const run=()=>{if(text.trim().length<40)return;const material=analyzeMaterial(title,text,active);add(material);setCreated(material.id)};const current=materials.find(m=>m.id===created)??materials[0]
 return <div className="page"><div className="page-heading"><span className="eyebrow">MEIN MATERIAL</span><h1>Aus jedem Text wird eine Lektion.</h1><p>Ngjit një email, shpallje pune ose artikull. DeutschCoach nxjerr fjalët dhe krijon ushtrime lokalisht.</p></div><div className="import-layout"><Card className="import-form"><label>Titulli<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="p.sh. Shpallje pune"/></label><label>Niveli<div className="mini-tabs">{(['A1','A2','B1','B2'] as GermanLevel[]).map(l=><button className={active===l?'active':''} onClick={()=>setActive(l)} key={l}>{l}</button>)}</div></label><label>Teksti gjerman<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Füge hier deinen deutschen Text ein …"/></label><Button onClick={run} disabled={text.trim().length<40}><Upload/> Krijo materialin</Button><small>Analiza bëhet në pajisjen tënde; teksti nuk dërgohet te një shërbim AI.</small></Card><div className="material-result">{current?<Card><div className="material-title"><div><LevelBadge level={current.level}/><h2>{current.title}</h2></div><button onClick={()=>remove(current.id)}><Trash2/></button></div><h3><Languages/> Fjalët kryesore</h3><div className="extracted-words">{current.words.map(w=><span key={w.word}><b>{w.word}</b>{w.meaning}</span>)}</div><h3><Sparkles/> Ushtrime të krijuara</h3>{current.exercises.map(ex=><div className="generated-exercise" key={ex.id}><small>{ex.skill}</small><b>{ex.prompt}</b><details><summary>Shfaq përgjigjen</summary><p>{ex.answer}</p><span>{ex.explanation}</span></details></div>)}</Card>:<Card className="empty-state"><BookOpenCheck/><strong>Materiali yt do të shfaqet këtu</strong><span>Ngjit të paktën 40 karaktere për të filluar.</span></Card>}</div></div>{materials.length>1&&<div className="material-history"><h2>Materialet e ruajtura</h2>{materials.map(m=><button onClick={()=>setCreated(m.id)} key={m.id}><LevelBadge level={m.level}/><span>{m.title}<small>{m.words.length} fjalë · {m.exercises.length} ushtrime</small></span><ArrowRight/></button>)}</div>}</div>}
