import { useMemo, useState } from 'react'
import { ArrowRight, Check, ChevronRight, RotateCcw, Sparkles, X } from 'lucide-react'
import { Button, Card, LevelBadge, ProgressBar } from '../components/ui'
import { exercises } from '../data/content'
import { validateAnswer } from '../engine/grammar'
import { useAppStore } from '../store/useAppStore'
import { LearningHelp } from '../components/LearningHelp'

export default function Practice(){const level=useAppStore(s=>s.profile.currentLevel);const record=useAppStore(s=>s.recordExercise);const list=useMemo(()=>exercises.filter(e=>e.level===level),[level]);const [index,setIndex]=useState(0);const [answer,setAnswer]=useState('');const [result,setResult]=useState<null|boolean>(null);const [done,setDone]=useState(0);const ex=list[index]
 const check=()=>{if(!answer.trim())return;const r=validateAnswer(answer,ex.answer);setResult(r.correct);record(r.correct);if(r.correct)setDone(x=>x+1)};const next=()=>{setIndex((index+1)%list.length);setAnswer('');setResult(null)}
 return <div className="page practice-page"><div className="practice-head"><div><span className="eyebrow">TÄGLICH ÜBEN</span><h1>Übung macht sicher.</h1><p>{exercises.filter(e=>e.level===level).length} ushtrime të ndryshme në nivelin {level}.</p></div><div className="practice-score"><Sparkles/>{done*10} XP</div></div><LearningHelp area="practice"/><div className="practice-progress"><span>Aufgabe {index+1} von {list.length}</span><ProgressBar value={(index+1)/list.length*100}/></div><Card className="exercise-card"><div className="exercise-meta"><LevelBadge level={ex.level}/><span>{ex.skill}</span><span>{ex.type==='choice'?'Wähle die richtige Antwort':ex.type==='order'?'Bilde einen Satz':'Schreibe deine Antwort'}</span></div><h2>{ex.prompt}</h2>{ex.options?<div className="answer-options">{ex.options.map((o,i)=><button key={o} className={`${answer===o?'selected':''} ${result!==null&&o===ex.answer?'correct':''} ${result===false&&answer===o?'wrong':''}`} onClick={()=>result===null&&setAnswer(o)}><span>{String.fromCharCode(65+i)}</span>{o}{result!==null&&o===ex.answer&&<Check/>}</button>)}</div>:<textarea value={answer} onChange={e=>setAnswer(e.target.value)} disabled={result!==null} placeholder="Schreibe auf Deutsch…"/>}{result!==null&&<div className={`feedback ${result?'good':'bad'}`}>{result?<Check/>:<X/>}<div><strong>{result?'Sehr gut!':'Fast — schau genau hin.'}</strong>{!result&&<p>Richtige Antwort: <b>{ex.answer}</b></p>}<p>{ex.explanation}</p></div></div>}<div className="exercise-actions">{result===null?<Button onClick={check} disabled={!answer.trim()}>Prüfen <ChevronRight/></Button>:<Button onClick={next}>Nächste Aufgabe <ArrowRight/></Button>}</div></Card><button className="reset-practice" onClick={()=>{setIndex(0);setAnswer('');setResult(null);setDone(0)}}><RotateCcw/> Serie neu starten</button></div>}
