import { Check, ChevronDown, Eye, FileText, Lightbulb, PenLine, RotateCcw, Volume2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { AudioButton, Button, Card, LevelBadge } from '../components/ui'
import { LearningHelp } from '../components/LearningHelp'
import { readingTexts, writingPrompts } from '../data/content'
import { useAppStore } from '../store/useAppStore'
import type { GermanLevel } from '../types'

export function Reading(){const current=useAppStore(s=>s.profile.currentLevel);const showTranslations=useAppStore(s=>s.profile.showTranslations);const [level,setLevel]=useState<GermanLevel>(current);const [showSq,setShowSq]=useState(showTranslations);const [answers,setAnswers]=useState<Record<number,string>>({});const text=useMemo(()=>readingTexts.find(x=>x.level===level)!,[level])
 return <div className="page"><div className="page-heading"><span className="eyebrow">LESETRAINING</span><h1>Lesen und wirklich verstehen.</h1><p>Tekste reale me fjalor, përkthim rezervë dhe pyetje kuptimi.</p></div><LearningHelp area="reading"/><div className="level-tabs compact">{(['A1','A2','B1','B2'] as GermanLevel[]).map(l=><button key={l} className={level===l?'active':''} onClick={()=>{setLevel(l);setAnswers({})}}><b>{l}</b></button>)}</div><Card className="reading-card"><div className="reading-head"><div><LevelBadge level={text.level}/><small>{text.topic}</small><h2>{text.title}</h2></div><AudioButton text={text.text} label="Text hören"/></div><p className="reading-text">{text.text}</p><button className="translation-toggle" onClick={()=>setShowSq(!showSq)}><LanguagesIcon/>{showSq?'Fshih përkthimin':'Shfaq kuptimin në shqip'}<ChevronDown/></button>{showSq&&<p className="reading-translation">{text.translation}</p>}<div className="text-vocab"><strong>Fjalë kyçe</strong>{text.vocabulary.map(v=><span key={v.de}><b>{v.de}</b> — {v.sq}</span>)}</div></Card><section className="reading-questions"><h2>Hast du alles verstanden?</h2>{text.questions.map((q,i)=><Card key={q.prompt}><h3>{i+1}. {q.prompt}</h3><div className="answer-options">{q.options.map(o=>{const selected=answers[i]===o;const checked=i in answers;return <button key={o} onClick={()=>!checked&&setAnswers(a=>({...a,[i]:o}))} className={`${selected?'selected':''} ${checked&&o===q.answer?'correct':''} ${checked&&selected&&o!==q.answer?'wrong':''}`}>{o}{checked&&o===q.answer&&<Check/>}</button>})}</div>{i in answers&&<p className="answer-explain"><Lightbulb/>{q.explanation}</p>}</Card>)}</section></div>}

function LanguagesIcon(){return <Volume2 aria-hidden="true"/>}

export function Writing(){const current=useAppStore(s=>s.profile.currentLevel);const [level,setLevel]=useState<GermanLevel>(current);const [draft,setDraft]=useState('');const [model,setModel]=useState(false);const prompt=writingPrompts.find(x=>x.level===level)!;const words=draft.trim()?draft.trim().split(/\s+/).length:0;const checks=[draft.length>30,/[.!?]/.test(draft),prompt.phrases.some(p=>draft.toLowerCase().includes(p.de.split(' ').slice(0,2).join(' ').toLowerCase()))]
 return <div className="page"><div className="page-heading"><span className="eyebrow">SCHREIBTRAINING</span><h1>Schreiben mit einem Gerüst.</h1><p>Detyrë, fraza ndihmëse, listë kontrolli dhe model — pa mbetur bosh.</p></div><LearningHelp area="writing"/><div className="level-tabs compact">{(['A1','A2','B1','B2'] as GermanLevel[]).map(l=><button key={l} className={level===l?'active':''} onClick={()=>{setLevel(l);setDraft('');setModel(false)}}><b>{l}</b></button>)}</div><div className="writing-layout"><Card className="writing-brief"><div><LevelBadge level={prompt.level}/><small>SCHREIBAUFGABE</small></div><h2>{prompt.title}</h2><p><b>Situata:</b> {prompt.situation}</p><div className="task-box"><FileText/><p><b>Detyra</b>{prompt.task}</p></div><h3>Fraza që të ndihmojnë</h3>{prompt.phrases.map(p=><div className="writing-phrase" key={p.de}><div><b>{p.de}</b><span>{p.sq}</span></div><AudioButton text={p.de} label=""/></div>)}<h3>Kontrollo para se ta mbarosh</h3><ul className="check-list">{prompt.checklist.map(x=><li key={x}><Check/>{x}</li>)}</ul></Card><Card className="writing-workspace"><div className="editor-head"><span><PenLine/><b>Teksti yt</b></span><small>{words} fjalë</small></div><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Schreibe hier auf Deutsch …"/><div className="self-check">{['Ke shkruar një përgjigje të plotë','Ke përdorur pikësim','Ke përdorur një frazë ndihmëse'].map((x,i)=><span className={checks[i]?'done':''} key={x}><Check/>{x}</span>)}</div><div className="writing-actions"><Button variant="ghost" onClick={()=>setDraft('')}><RotateCcw/> Pastro</Button><Button variant="secondary" onClick={()=>setModel(!model)}><Eye/> {model?'Fshih modelin':'Shiko modelin'}</Button></div>{model&&<div className="model-answer"><strong>Modelantwort</strong><p>{prompt.model}</p><span>{prompt.modelSq}</span></div>}</Card></div></div>}
