import { useEffect, useRef, useState } from 'react'
import { AlertCircle, ArrowLeft, BarChart3, BriefcaseBusiness, Check, Headphones, MessageCircle, Mic2, RotateCcw, Square, Volume2 } from 'lucide-react'
import { Button, Card, LevelBadge, ProgressBar } from '../components/ui'
import { conversations } from '../data/content'
import { coachService, speakGerman } from '../engine/coach'
import { useAppStore } from '../store/useAppStore'
import type { Conversation, ConversationTurn } from '../types'
import { LearningHelp } from '../components/LearningHelp'

function useRecognition(onText:(text:string)=>void){const [listening,setListening]=useState(false);const [error,setError]=useState('');const rec=useRef<SpeechRecognition>();const supported=!!(window.SpeechRecognition||window.webkitSpeechRecognition)
 const start=()=>{setError('');const C=window.SpeechRecognition||window.webkitSpeechRecognition;if(!C){setError('Njohja e zërit nuk mbështetet. Provo Chrome në Android.');return}const r=new C();r.lang='de-DE';r.continuous=false;r.interimResults=false;r.onresult=e=>onText(e.results[0][0].transcript);r.onerror=e=>{setError(e.error==='not-allowed'?'Leja e mikrofonit u refuzua. Lejo mikrofonin në cilësimet e shfletuesit.':'Nuk u dëgjua qartë. Provo përsëri.');setListening(false)};r.onend=()=>setListening(false);rec.current=r;r.start();setListening(true)};const stop=()=>{rec.current?.stop();setListening(false)};return{supported,listening,error,start,stop}}

export default function Speaking({callCenter=false}:{callCenter?:boolean}){const level=useAppStore(s=>s.profile.currentLevel);const rate=useAppStore(s=>s.profile.speechRate);const addMistake=useAppStore(s=>s.addMistake);const recordSpeaking=useAppStore(s=>s.recordSpeaking);const choices=conversations.filter(c=>callCenter?c.category==='Callcenter':c.level===level);const [scenario,setScenario]=useState<Conversation|null>(null);const [turns,setTurns]=useState<ConversationTurn[]>([]);const [transcript,setTranscript]=useState('');const [typing,setTyping]=useState(false);const [report,setReport]=useState(false);const started=useRef(Date.now());
 const process=async(text:string)=>{if(!scenario||!text.trim())return;setTranscript(text);const response=await coachService.engine.respond(text,{level:scenario.level,scenario,turns});const next=[...turns,{speaker:'user' as const,text,correction:response.correction},{speaker:'coach' as const,text:response.reply}];setTurns(next);if(response.correction.issues.length)addMistake({original:text,correction:response.correction.corrected,topic:response.correction.issues[0],level:scenario.level});speakGerman(response.reply,rate);setTyping(false)}
 const speech=useRecognition(process);const begin=(s:Conversation)=>{setScenario(s);setTurns([{speaker:'coach',text:s.opening}]);setReport(false);started.current=Date.now();setTimeout(()=>speakGerman(s.opening,rate),200)};const end=()=>{recordSpeaking(Math.max(1,Math.round((Date.now()-started.current)/60000)));setReport(true)}
 if(!scenario)return <div className="page"><div className={`page-heading ${callCenter?'call-heading':''}`}><span className="eyebrow">{callCenter?'CALL CENTER DEUTSCH':'MEIN DEUTSCH-COACH'}</span><h1>{callCenter?'Professionell bleiben. Klar helfen.':'Deutsch sprechen. Ohne Angst.'}</h1><p>{callCenter?'Realistische Kundengespräche mit Stimmung, Ziel und verzweigter Reaktion.':'Zgjidh një situatë. Coach-i flet gjermanisht, të korrigjon dhe vazhdon bisedën.'}</p></div><LearningHelp area="speaking"/>{callCenter&&<Card className="call-hero"><BriefcaseBusiness/><div><span className="eyebrow">DEIN BERUFSZIEL</span><h2>Fit für den deutschen Kundenservice</h2><p>Trainiere höfliche Sprache, aktives Zuhören und Deeskalation — lokal und ohne bezahlte KI.</p></div><div><b>{choices.length}</b><span>Simulationen</span></div></Card>}<div className="scenario-grid">{choices.map(s=><Card className="scenario-card" key={s.id}><div><LevelBadge level={s.level}/><span className="category">{s.category}</span>{s.mood&&<span className="mood">{s.mood}</span>}</div><span className="scenario-icon">{s.category==='Callcenter'?<Headphones/>:<MessageCircle/>}</span><h3>{s.title}</h3><p>{s.goal}</p><div className="opening-preview">„{s.opening}”</div><Button onClick={()=>begin(s)}>Simulation starten <Mic2/></Button></Card>)}</div>{!speech.supported&&<div className="support-note"><AlertCircle/> SpeechRecognition nuk është i disponueshëm këtu. Mund të shkruash përgjigjet; për zë provo Chrome në Android.</div>}</div>
 if(report){const attempts=turns.filter(t=>t.speaker==='user');const avg=attempts.length?Math.round(attempts.reduce((a,t)=>a+(t.correction?.scores.overall||0),0)/attempts.length):0;return <div className="page report-page"><Card><div className="report-check"><Check/></div><span className="eyebrow">SESSION ABGESCHLOSSEN</span><h1>Starke Arbeit.</h1><p>Du hast das Gespräch aktiv auf Deutsch geführt.</p><div className="report-score"><span><b>{avg}%</b>Übungsscore</span><span><b>{attempts.length}</b>Antworten</span><span><b>{attempts.filter(t=>t.correction?.issues.length).length}</b>Fehler gespeichert</span></div><div className="recommend"><BarChart3/><div><strong>Als Nächstes üben</strong><span>{attempts.flatMap(t=>t.correction?.issues||[]).slice(0,3).join(' · ')||'Längere vollständige Sätze'}</span></div></div><Button onClick={()=>{setScenario(null);setTurns([])}}>Neue Simulation</Button></Card></div>}
 const latest=[...turns].reverse().find(t=>t.speaker==='user')?.correction
 return <div className="speaking-session"><header><button onClick={()=>setScenario(null)}><ArrowLeft/></button><div><LevelBadge level={scenario.level}/><strong>{scenario.title}</strong></div><button onClick={end}>Beenden</button></header><div className="session-body"><div className="conversation-panel"><div className="coach-status"><span>M</span><div><strong>Dein Deutsch-Coach</strong><small><i/> LOKALER COACH · {scenario.level}</small></div><button onClick={()=>speakGerman(turns.filter(t=>t.speaker==='coach').at(-1)?.text||scenario.opening,rate)}><Volume2/></button></div><div className="bubbles">{turns.map((t,i)=><div key={i} className={`bubble ${t.speaker}`}><small>{t.speaker==='coach'?'COACH':'DU'}</small><p>{t.text}</p>{t.speaker==='coach'&&<button onClick={()=>speakGerman(t.text,rate)}><Volume2/> Nochmal hören</button>}</div>)}</div>{latest&&<Card className="correction-card"><div className="correction-title"><Check/><strong>Korrektur & Feedback</strong><span>Übungsscore {latest.scores.overall}%</span></div><div className="correction-grid"><div><small>DU HAST GESAGT</small><p>{latest.original}</p></div><div><small>BESSERES DEUTSCH</small><p>{latest.corrected}</p></div></div><div className="why"><strong>Warum?</strong><span>{latest.explanationDe}</span><em>{latest.explanationSq}</em></div></Card>}</div><aside className="session-aside"><Card><span className="eyebrow">DEIN ZIEL</span><p>{scenario.goal}</p><ProgressBar value={Math.min(100,turns.filter(t=>t.speaker==='user').length/scenario.intents.length*100)}/></Card><Card><span className="eyebrow">NÄCHSTER TIPP</span><p>{scenario.intents[Math.min(scenario.intents.length-1,turns.filter(t=>t.speaker==='user').length)]?.hint}</p></Card></aside></div><div className="speech-dock">{speech.error&&<span className="speech-error"><AlertCircle/>{speech.error}</span>}{typing?<form onSubmit={e=>{e.preventDefault();process(transcript)}}><input autoFocus value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="Auf Deutsch antworten…"/><Button type="submit">Senden</Button></form>:<><button className={`mic-button ${speech.listening?'listening':''}`} onClick={speech.listening?speech.stop:speech.start} aria-label={speech.listening?'Aufnahme stoppen':'Deutsch sprechen'}>{speech.listening?<Square/>:<Mic2/>}</button><div><strong>{speech.listening?'Ich höre zu…':'Sprich Deutsch'}</strong><span>{speech.listening?'Sag einen vollständigen Satz.':'Tippe auf das Mikrofon.'}</span></div><button className="type-toggle" onClick={()=>setTyping(true)}>Oder tippen</button></>}</div></div>}
