import { useMemo, useState } from 'react'
import { Bookmark, BookmarkCheck, Check, RotateCcw, Search, Volume2 } from 'lucide-react'
import { AudioButton, Card, LevelBadge } from '../components/ui'
import { vocabulary } from '../data/content'
import { useAppStore } from '../store/useAppStore'
import type { GermanLevel } from '../types'

export default function Vocabulary(){const level=useAppStore(s=>s.profile.currentLevel);const [active,setActive]=useState<GermanLevel>(level);const [q,setQ]=useState('');const [topic,setTopic]=useState('Alle');const saved=useAppStore(s=>s.savedWords);const toggle=useAppStore(s=>s.toggleWord);const review=useAppStore(s=>s.reviewWord);const topics=['Alle',...new Set(vocabulary.filter(v=>v.level===active).map(v=>v.topic))];const shown=useMemo(()=>vocabulary.filter(v=>v.level===active&&(topic==='Alle'||v.topic===topic)&&(`${v.article??''} ${v.word} ${v.translation}`.toLowerCase().includes(q.toLowerCase()))),[active,topic,q]);
 return <div className="page"><div className="page-heading"><span className="eyebrow">WORT FÜR WORT</span><h1>Wortschatz, den du wirklich brauchst.</h1><p>Me artikull, shumës, shembull dhe përsëritje të planifikuar.</p></div><div className="toolbar"><div className="search-field"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Wort oder përkthim…"/></div><div className="mini-tabs">{(['A1','A2','B1','B2'] as GermanLevel[]).map(l=><button className={l===active?'active':''} onClick={()=>setActive(l)} key={l}>{l}</button>)}</div></div><div className="topic-chips">{topics.map(t=><button key={t} className={topic===t?'active':''} onClick={()=>setTopic(t)}>{t}</button>)}</div><div className="vocab-count"><span>{shown.length} Wörter</span><span><BookmarkCheck/> {saved.length} te Meine Wörter</span></div><div className="vocab-grid">{shown.map(v=><Card className="vocab-card" key={v.id}><div className="vocab-top"><LevelBadge level={v.level}/><button onClick={()=>toggle(v.id)} aria-label="Te fjalët e mia">{saved.includes(v.id)?<BookmarkCheck/>:<Bookmark/>}</button></div><h3>{v.article&&<small>{v.article}</small>} {v.word}</h3><p className="translation">{v.translation}</p>{v.plural&&<span className="plural">Plural: die {v.plural}</span>}<div className="vocab-example"><p>{v.example}</p><AudioButton text={v.example} label=""/></div><div className="review-actions"><button onClick={()=>review(v.id,false)}><RotateCcw/> Vështirë</button><button onClick={()=>review(v.id,true)}><Check/> E dija</button></div></Card>)}</div></div>}
